version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306": "3306"

  app:
    build: ./app
    container_name: java-app
    depends_on:
      - mysql
    ports:
      - "8080": "8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/app_db
      DB_USER: app_user
      DB_PASSWORD: app_pass

volumes:
  mysql_data: